(function(){
'use strict';
const state={divisions:[],regions:[],parks:[],users:[],assignments:[],history:[],tab:'parks'};
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const client=()=>window.ParksCloud?.client?.();
const isArchitect=()=>window.ParksPermissions?.realRole?.()==='arquitecto';
const notify=m=>window.toast?window.toast(m):console.log(m);
function requireArchitect(){if(!isArchitect())throw new Error('Solo el Arquitecto del Sistema puede modificar la configuración maestra.');}
function statusLabel(s){return s==='activo'?'Activo':s==='construccion'?'En construcción':s==='adquirido'?'Adquirido':s==='baja'?'Baja':s||'Activo'}
function statusBadge(s){const cls=s==='activo'?'master-active':(s==='construccion'||s==='adquirido')?'master-build':'master-inactive';return `<span class="master-badge ${cls}">${esc(statusLabel(s))}</span>`}
function regionOf(park){return state.regions.find(r=>r.id===park.region_id)||{}}
function divisionOfRegion(region){return state.divisions.find(d=>d.id===region?.division_id)||{}}
function userAssignments(userId){return state.assignments.filter(a=>a.user_id===userId&&!a.valid_to)}
async function safeSelect(table,select,extra){let q=client().from(table).select(select);if(extra)q=extra(q);const r=await q; if(r.error){if(['42P01','42703'].includes(r.error.code))return [];throw r.error}return r.data||[]}
async function load(){if(!client())return; const [divisions,regions,parks,users,assignments,history]=await Promise.all([
 safeSelect('divisions','id,code,name,is_active,created_at,updated_at',q=>q.order('code')),
 safeSelect('regions','id,code,name,division_id,is_active,sort_order',q=>q.order('sort_order')),
 safeSelect('parks','id,code,name,commercial_name,region_id,status,administrator_name,created_at,updated_at',q=>q.order('name')),
 safeSelect('profiles','id,full_name,email,role,is_active,status',q=>q.in('role',['administrador','regional','divisional']).order('full_name')),
 safeSelect('park_assignments','id,park_id,user_id,is_primary,valid_from,valid_to,created_at',q=>q.is('valid_to',null).order('created_at')),
 safeSelect('org_change_history','id,entity_type,entity_id,field_name,old_value,new_value,effective_from,changed_by,change_reason,created_at',q=>q.order('effective_from',{ascending:false}).limit(300))
 ]); Object.assign(state,{divisions,regions,parks,users,assignments,history}); render();}
function renderKpis(){const active=state.parks.filter(p=>p.status==='activo').length;$('#masterKpis').innerHTML=[['Parques activos',active],['En construcción / adquiridos',state.parks.filter(p=>['construccion','adquirido'].includes(p.status)).length],['Regiones',state.regions.filter(r=>r.is_active!==false).length],['Divisiones',state.divisions.filter(d=>d.is_active!==false).length]].map(([a,b])=>`<div class="card master-kpi"><small>${a}</small><strong>${b}</strong></div>`).join('')}
function render(){const root=$('#configuracionMaestra');if(!root)return; renderKpis(); root.querySelectorAll('[data-master-tab]').forEach(b=>b.classList.toggle('active',b.dataset.masterTab===state.tab)); const fn={parks:renderParks,regions:renderRegions,divisions:renderDivisions,assignments:renderAssignments,history:renderHistory}[state.tab]; fn&&fn();}
function renderParks(){const rows=state.parks.map(p=>{const r=regionOf(p),d=divisionOfRegion(r),admins=state.assignments.filter(a=>a.park_id===p.id&&!a.valid_to).map(a=>state.users.find(u=>u.id===a.user_id)?.full_name).filter(Boolean);return `<tr><td><b>${esc(p.commercial_name||p.name)}</b><br><small>${esc(p.code||'')}</small></td><td>${esc(d.code||d.name||'Sin división')}</td><td>${esc(r.code||r.name||'Sin región')}</td><td>${admins.length?admins.map(esc).join('<br>'):'Sin responsable directo'}</td><td>${statusBadge(p.status)}</td><td><div class="master-actions"><button class="btn secondary" data-edit-park="${p.id}">Editar / mover</button><button class="btn ghost" data-assign-park="${p.id}">Asignar</button></div></td></tr>`}).join('');$('#masterView').innerHTML=`<div class="master-toolbar"><input id="masterParkSearch" placeholder="Buscar parque..."><select id="masterParkRegion"><option value="">Todas las regiones</option>${state.regions.map(r=>`<option value="${r.id}">${esc(r.code)} · ${esc(r.name)}</option>`).join('')}</select></div><div class="master-table-wrap"><table class="master-table"><thead><tr><th>Parque</th><th>División</th><th>Región</th><th>Responsables directos</th><th>Estatus</th><th>Acciones</th></tr></thead><tbody id="masterParksBody">${rows}</tbody></table></div>`;bindParkFilters();}
function bindParkFilters(){const search=$('#masterParkSearch'),reg=$('#masterParkRegion');const apply=()=>{const q=(search.value||'').toLowerCase(),rid=reg.value;document.querySelectorAll('#masterParksBody tr').forEach(tr=>{const p=state.parks[[...document.querySelectorAll('#masterParksBody tr')].indexOf(tr)];tr.style.display=((!q||tr.textContent.toLowerCase().includes(q))&&(!rid||p?.region_id===rid))?'':'none'})};search?.addEventListener('input',apply);reg?.addEventListener('change',apply)}
function renderRegions(){const rows=state.regions.map(r=>{const d=divisionOfRegion(r),count=state.parks.filter(p=>p.region_id===r.id&&p.status!=='baja').length;return `<tr><td><b>${esc(r.code)}</b><br><small>${esc(r.name)}</small></td><td>${esc(d.code||d.name||'Sin división')}</td><td>${count}</td><td>${r.is_active===false?statusBadge('baja'):statusBadge('activo')}</td><td><button class="btn secondary" data-edit-region="${r.id}">Editar / mover</button></td></tr>`}).join('');$('#masterView').innerHTML=`<div class="master-toolbar"><b>Regiones operativas</b><button class="btn primary" id="masterNewRegion">+ Nueva región</button></div><div class="master-table-wrap"><table class="master-table"><thead><tr><th>Región</th><th>División</th><th>Parques</th><th>Estatus</th><th></th></tr></thead><tbody>${rows}</tbody></table></div>`}
function renderDivisions(){const rows=state.divisions.map(d=>{const regs=state.regions.filter(r=>r.division_id===d.id&&r.is_active!==false);const parks=state.parks.filter(p=>regs.some(r=>r.id===p.region_id)&&p.status!=='baja').length;return `<tr><td><b>${esc(d.code)}</b><br><small>${esc(d.name)}</small></td><td>${regs.length}</td><td>${parks}</td><td>${d.is_active===false?statusBadge('baja'):statusBadge('activo')}</td><td><button class="btn secondary" data-edit-division="${d.id}">Editar</button></td></tr>`}).join('');$('#masterView').innerHTML=`<div class="master-toolbar"><b>Divisiones</b><button class="btn primary" id="masterNewDivision">+ Nueva división</button></div><div class="master-table-wrap"><table class="master-table"><thead><tr><th>División</th><th>Regiones</th><th>Parques</th><th>Estatus</th><th></th></tr></thead><tbody>${rows}</tbody></table></div>`}
function renderAssignments(){const admins=state.users.filter(u=>u.role==='administrador');$('#masterView').innerHTML=`<div class="master-toolbar"><b>Responsabilidad directa de administradores</b><span style="color:var(--mut);font-size:12px">La asignación no limita el alcance: el Administrador opera toda su región.</span></div>${admins.map(u=>{const ass=userAssignments(u.id),parks=ass.map(a=>state.parks.find(p=>p.id===a.park_id)).filter(Boolean);return `<div class="master-assignment-card"><div style="display:flex;justify-content:space-between;gap:12px;align-items:center"><div><b>${esc(u.full_name||u.email)}</b><small style="display:block;color:var(--mut)">${esc(u.email||'')}</small></div><button class="btn secondary" data-assign-user="${u.id}">Editar parques</button></div><div class="master-assignment-parks">${parks.length?parks.map(p=>`<span class="master-chip">${esc(p.commercial_name||p.name)}</span>`).join(''):'<span style="color:var(--mut);font-size:12px">Sin parques de responsabilidad directa</span>'}</div></div>`}).join('')||'<div class="master-empty">No hay administradores.</div>'}`}
function renderHistory(){const rows=state.history.map(h=>{const who=state.users.find(u=>u.id===h.changed_by)?.full_name||'';return `<tr><td>${new Date(h.effective_from||h.created_at).toLocaleString('es-MX')}</td><td>${esc(h.entity_type)}</td><td><b>${esc(h.field_name)}</b></td><td><div class="master-history-change"><small>${esc(formatValue(h.old_value))}</small><span>→</span><small>${esc(formatValue(h.new_value))}</small></div></td><td>${esc(h.change_reason||'')}</td><td>${esc(who)}</td></tr>`}).join('');$('#masterView').innerHTML=`<div class="master-toolbar"><b>Historial de estructura</b><input id="masterHistorySearch" placeholder="Buscar cambio, motivo o entidad..."></div><div class="master-table-wrap"><table class="master-table"><thead><tr><th>Fecha efectiva</th><th>Entidad</th><th>Cambio</th><th>Antes → después</th><th>Motivo</th><th>Usuario</th></tr></thead><tbody id="masterHistoryBody">${rows}</tbody></table></div>`;$('#masterHistorySearch')?.addEventListener('input',e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('#masterHistoryBody tr').forEach(tr=>tr.style.display=!q||tr.textContent.toLowerCase().includes(q)?'':'none')})}
function formatValue(v){if(v==null)return '—';if(typeof v==='string')return v;try{return JSON.stringify(v)}catch{return String(v)}}
async function logChange(entityType,entityId,field,oldValue,newValue,reason,effectiveFrom){const me=window.ParksCloud?.profile?.()||{};const row={entity_type:entityType,entity_id:entityId,field_name:field,old_value:oldValue==null?null:oldValue,new_value:newValue==null?null:newValue,effective_from:effectiveFrom||new Date().toISOString(),changed_by:me.id||null,change_reason:reason||null};const r=await client().from('org_change_history').insert(row);if(r.error)throw r.error}
function modal(title,body){window.openModal(title,body)}
function parkForm(p=null){requireArchitect();const oldR=regionOf(p||{}),oldD=divisionOfRegion(oldR);modal(p?'Editar / mover parque':'Nuevo parque',`<form id="masterParkForm"><div class="master-form-grid"><label>Nombre comercial<input name="commercial_name" required value="${esc(p?.commercial_name||p?.name||'')}"></label><label>Clave<input name="code" required value="${esc(p?.code||'')}"></label><label>Región<select name="region_id" required>${state.regions.filter(r=>r.is_active!==false).map(r=>`<option value="${r.id}" ${p?.region_id===r.id?'selected':''}>${esc(r.code)} · ${esc(r.name)} · ${esc(divisionOfRegion(r).code||'')}</option>`).join('')}</select></label><label>Estatus<select name="status">${['activo','construccion','adquirido','baja'].map(x=>`<option value="${x}" ${p?.status===x?'selected':''}>${statusLabel(x)}</option>`).join('')}</select></label><label class="full">Motivo del cambio<textarea name="reason" ${p?'required':''} placeholder="Ej. Reestructura operativa, adquisición, cambio de cobertura..."></textarea></label><label>Vigente desde<input type="datetime-local" name="effective_from"></label></div><div style="display:flex;justify-content:flex-end;gap:8px;margin-top:16px"><button class="btn secondary" type="button" onclick="closeModal()">Cancelar</button><button class="btn primary" type="submit">Guardar</button></div></form>`);$('#masterParkForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),payload={name:String(f.get('commercial_name')).trim(),commercial_name:String(f.get('commercial_name')).trim(),code:String(f.get('code')).trim(),region_id:f.get('region_id'),status:f.get('status')},reason=String(f.get('reason')||'').trim(),effective=f.get('effective_from')?new Date(f.get('effective_from')).toISOString():new Date().toISOString();try{requireArchitect();if(p){const r=await client().from('parks').update(payload).eq('id',p.id);if(r.error)throw r.error;if(p.region_id!==payload.region_id)await logChange('parque',p.id,'region_id',{id:p.region_id,code:oldR.code,division:oldD.code},{id:payload.region_id,code:state.regions.find(x=>x.id===payload.region_id)?.code,division:divisionOfRegion(state.regions.find(x=>x.id===payload.region_id)).code},reason,effective);if(p.status!==payload.status)await logChange('parque',p.id,'status',p.status,payload.status,reason,effective);if((p.commercial_name||p.name)!==payload.commercial_name)await logChange('parque',p.id,'nombre',p.commercial_name||p.name,payload.commercial_name,reason,effective)}else{const r=await client().from('parks').insert(payload).select('id').single();if(r.error)throw r.error;await logChange('parque',r.data.id,'alta',null,payload,reason||'Alta de nuevo parque',effective)}window.closeModal();await afterChange('Catálogo de parques actualizado.')}catch(err){alert(err.message)}}}
function regionForm(r=null){requireArchitect();modal(r?'Editar / mover región':'Nueva región',`<form id="masterRegionForm"><div class="master-form-grid"><label>Clave<input name="code" required value="${esc(r?.code||'')}"></label><label>Nombre<input name="name" required value="${esc(r?.name||'')}"></label><label>División<select name="division_id" required>${state.divisions.filter(d=>d.is_active!==false).map(d=>`<option value="${d.id}" ${r?.division_id===d.id?'selected':''}>${esc(d.code)} · ${esc(d.name)}</option>`).join('')}</select></label><label>Estatus<select name="is_active"><option value="true" ${r?.is_active!==false?'selected':''}>Activa</option><option value="false" ${r?.is_active===false?'selected':''}>Inactiva</option></select></label><label class="full">Motivo<textarea name="reason" ${r?'required':''}></textarea></label></div><div style="text-align:right;margin-top:16px"><button class="btn primary">Guardar</button></div></form>`);$('#masterRegionForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),payload={code:String(f.get('code')).trim(),name:String(f.get('name')).trim(),division_id:f.get('division_id'),is_active:f.get('is_active')==='true'},reason=String(f.get('reason')||'').trim();try{if(r){const q=await client().from('regions').update(payload).eq('id',r.id);if(q.error)throw q.error;if(r.division_id!==payload.division_id)await logChange('region',r.id,'division_id',r.division_id,payload.division_id,reason)}else{const q=await client().from('regions').insert(payload).select('id').single();if(q.error)throw q.error;await logChange('region',q.data.id,'alta',null,payload,reason||'Alta de región')}window.closeModal();await afterChange('Región actualizada.')}catch(err){alert(err.message)}}}
function divisionForm(d=null){requireArchitect();modal(d?'Editar división':'Nueva división',`<form id="masterDivisionForm"><div class="master-form-grid"><label>Clave<input name="code" required value="${esc(d?.code||'')}"></label><label>Nombre<input name="name" required value="${esc(d?.name||'')}"></label><label>Estatus<select name="is_active"><option value="true" ${d?.is_active!==false?'selected':''}>Activa</option><option value="false" ${d?.is_active===false?'selected':''}>Inactiva</option></select></label><label class="full">Motivo<textarea name="reason" ${d?'required':''}></textarea></label></div><div style="text-align:right;margin-top:16px"><button class="btn primary">Guardar</button></div></form>`);$('#masterDivisionForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),payload={code:String(f.get('code')).trim(),name:String(f.get('name')).trim(),is_active:f.get('is_active')==='true'},reason=String(f.get('reason')||'').trim();try{if(d){const q=await client().from('divisions').update(payload).eq('id',d.id);if(q.error)throw q.error;await logChange('division',d.id,'edicion',{code:d.code,name:d.name,is_active:d.is_active},payload,reason)}else{const q=await client().from('divisions').insert(payload).select('id').single();if(q.error)throw q.error;await logChange('division',q.data.id,'alta',null,payload,reason||'Alta de división')}window.closeModal();await afterChange('División actualizada.')}catch(err){alert(err.message)}}}
function assignmentForm({userId=null,parkId=null}={}){requireArchitect();const user=userId?state.users.find(u=>u.id===userId):null;const park=parkId?state.parks.find(p=>p.id===parkId):null;const admins=state.users.filter(u=>u.role==='administrador'&&u.is_active!==false);const selected=new Set(user?userAssignments(user.id).map(a=>a.park_id):park?state.assignments.filter(a=>a.park_id===park.id&&!a.valid_to).map(a=>a.user_id):[]);modal('Asignaciones de responsabilidad',`<form id="masterAssignmentForm"><div class="master-form-grid">${user?`<label class="full">Administrador<input value="${esc(user.full_name||user.email)}" disabled></label><label class="full">Parques asignados<select class="master-multiselect" name="ids" multiple>${state.parks.filter(p=>p.status!=='baja').map(p=>`<option value="${p.id}" ${selected.has(p.id)?'selected':''}>${esc(p.commercial_name||p.name)} · ${esc(regionOf(p).code||'')}</option>`).join('')}</select></label>`:`<label class="full">Parque<input value="${esc(park?.commercial_name||park?.name||'')}" disabled></label><label class="full">Administradores responsables<select class="master-multiselect" name="ids" multiple>${admins.map(u=>`<option value="${u.id}" ${selected.has(u.id)?'selected':''}>${esc(u.full_name||u.email)}</option>`).join('')}</select></label>`}<label class="full">Motivo<textarea name="reason" required placeholder="Ej. Asignación inicial, vacaciones, reestructura..."></textarea></label><label>Vigente desde<input type="datetime-local" name="effective_from"></label></div><div style="text-align:right;margin-top:16px"><button class="btn primary">Guardar asignaciones</button></div></form>`);$('#masterAssignmentForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),ids=new Set(f.getAll('ids').map(String)),reason=String(f.get('reason')||'').trim(),effective=f.get('effective_from')?new Date(f.get('effective_from')).toISOString():new Date().toISOString();try{if(user){await replaceUserAssignments(user.id,ids,reason,effective)}else{await replaceParkAssignments(park.id,ids,reason,effective)}window.closeModal();await afterChange('Asignaciones actualizadas.')}catch(err){alert(err.message)}}}
async function replaceUserAssignments(userId,newParkIds,reason,effective){const current=state.assignments.filter(a=>a.user_id===userId&&!a.valid_to),currentIds=new Set(current.map(a=>a.park_id));for(const a of current){if(!newParkIds.has(a.park_id)){let r=await client().from('park_assignments').update({valid_to:effective}).eq('id',a.id);if(r.error)throw r.error;await logChange('asignacion',a.id,'responsable',userId,null,reason,effective)}}for(const pid of newParkIds){if(!currentIds.has(pid)){let r=await client().from('park_assignments').insert({park_id:pid,user_id:userId,valid_from:effective,created_by:window.ParksCloud?.profile?.()?.id||null,change_reason:reason}).select('id').single();if(r.error)throw r.error;await logChange('asignacion',r.data.id,'responsable',null,{user_id:userId,park_id:pid},reason,effective)}}}
async function replaceParkAssignments(parkId,newUserIds,reason,effective){const current=state.assignments.filter(a=>a.park_id===parkId&&!a.valid_to),currentIds=new Set(current.map(a=>a.user_id));for(const a of current){if(!newUserIds.has(a.user_id)){let r=await client().from('park_assignments').update({valid_to:effective}).eq('id',a.id);if(r.error)throw r.error;await logChange('asignacion',a.id,'responsable',a.user_id,null,reason,effective)}}for(const uid of newUserIds){if(!currentIds.has(uid)){let r=await client().from('park_assignments').insert({park_id:parkId,user_id:uid,valid_from:effective,created_by:window.ParksCloud?.profile?.()?.id||null,change_reason:reason}).select('id').single();if(r.error)throw r.error;await logChange('asignacion',r.data.id,'responsable',null,{user_id:uid,park_id:parkId},reason,effective)}}}
async function afterChange(message){notify(message);await load();try{await window.ParksCloud?.refreshData?.(); if (typeof compute === 'function') { C = compute(); window.C = C; } window.dispatchEvent(new CustomEvent('parks:catalog-changed',{detail:{at:new Date().toISOString()}})); if (typeof window.renderAllAfterDecision === 'function') window.renderAllAfterDecision();}catch(e){console.warn('Recarga transversal pendiente:',e)}}
function bind(){document.addEventListener('click',e=>{const t=e.target.closest('[data-master-tab],[data-edit-park],[data-edit-region],[data-edit-division],[data-assign-user],[data-assign-park],#masterNewPark,#masterNewRegion,#masterNewDivision,#masterRefresh');if(!t)return;if(t.dataset.masterTab){state.tab=t.dataset.masterTab;render();return}if(t.id==='masterRefresh'){load();return}if(t.id==='masterNewPark'){parkForm();return}if(t.id==='masterNewRegion'){regionForm();return}if(t.id==='masterNewDivision'){divisionForm();return}if(t.dataset.editPark)parkForm(state.parks.find(p=>p.id===t.dataset.editPark));if(t.dataset.editRegion)regionForm(state.regions.find(r=>r.id===t.dataset.editRegion));if(t.dataset.editDivision)divisionForm(state.divisions.find(d=>d.id===t.dataset.editDivision));if(t.dataset.assignUser)assignmentForm({userId:t.dataset.assignUser});if(t.dataset.assignPark)assignmentForm({parkId:t.dataset.assignPark})});window.addEventListener('parks:auth-ready',load);setTimeout(()=>{if(window.ParksCloud?.session?.())load()},1400)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
window.ParksMaster={load,state};
})();
